# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 14:03
from __future__ import unicode_literals

from django.db import migrations
import salesforce.backend.operations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeCourse',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', salesforce.fields.BooleanField(default=False, verbose_name='Deleted')),
                ('name', salesforce.fields.CharField(blank=True, default=salesforce.backend.operations.DefaultedOnCreate(), max_length=80, null=True, verbose_name='Studiengang Name')),
                ('standard_period_of_study', salesforce.fields.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Regelstudienzeit (Semesteranzahl)')),
                ('start_of_studies', salesforce.fields.DateField(blank=True, null=True, verbose_name='Studienbeginn')),
                ('cost_per_month', salesforce.fields.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Kosten pro Monat > Regelstudienzeit')),
                ('number_of_sofortzahler_trig', salesforce.fields.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Anzahl Sofortzahler')),
                ('matriculation_fee', salesforce.fields.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Immatrikulationsgebühren')),
                ('semester_fee', salesforce.fields.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Semesterbeitrag')),
                ('total_tuition_fees_auto', salesforce.fields.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Studiengebühren gesamt')),
                ('start_summer_semester', salesforce.fields.CharField(blank=True, choices=[('Januar', 'Januar'), ('Februar', 'Februar'), ('März', 'März'), ('April', 'April'), ('Mai', 'Mai'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('August', 'August'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Dezember', 'Dezember')], max_length=255, null=True, verbose_name='Startmonat Sommersemester')),
                ('start_winter_semester', salesforce.fields.CharField(blank=True, choices=[('Januar', 'Januar'), ('Februar', 'Februar'), ('März', 'März'), ('April', 'April'), ('Mai', 'Mai'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('August', 'August'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Dezember', 'Dezember')], max_length=255, null=True, verbose_name='Startmonat Wintersemester')),
                ('start_of_studies_month', salesforce.fields.CharField(blank=True, choices=[('Januar', 'Januar'), ('Februar', 'Februar'), ('März', 'März'), ('April', 'April'), ('Mai', 'Mai'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('August', 'August'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Dezember', 'Dezember')], max_length=255, null=True, verbose_name='Startmonat Studienbeginn')),
                ('course_id', salesforce.fields.CharField(blank=True, max_length=1300, null=True, verbose_name='StudiengangID')),
            ],
            options={
                'verbose_name': 'Studiengang',
                'verbose_name_plural': 'Studiengänge',
                'db_table': 'DegreeCourse__c',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', salesforce.fields.BooleanField(default=False, verbose_name='Deleted')),
                ('name', salesforce.fields.CharField(blank=True, default=salesforce.backend.operations.DefaultedOnCreate(), max_length=80, null=True, verbose_name='Rechnung Name')),
                ('last_modified_date', salesforce.fields.DateTimeField()),
                ('university_ref', salesforce.fields.CharField(blank=True, max_length=1300, null=True, verbose_name='Hochschule')),
                ('student_id_ref', salesforce.fields.CharField(blank=True, max_length=1300, null=True, verbose_name='Studenten-ID')),
                ('period', salesforce.fields.CharField(blank=True, max_length=10, null=True)),
                ('total', salesforce.fields.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Rechnungsbetrag')),
                ('etsalutation_ref', salesforce.fields.CharField(blank=True, db_column='ETSalutationRef__c', max_length=1300, null=True, verbose_name='ETSalutation')),
                ('etfirst_name_ref', salesforce.fields.CharField(blank=True, db_column='ETFirstNameRef__c', max_length=1300, null=True, verbose_name='ETFirstName')),
                ('etlast_name_ref', salesforce.fields.CharField(blank=True, db_column='ETLastNameRef__c', max_length=1300, null=True, verbose_name='ETLastName')),
                ('etbilling_street_ref', salesforce.fields.CharField(blank=True, db_column='ETBillingStreetRef__c', max_length=1300, null=True, verbose_name='ETBillingStreet')),
                ('etbilling_zip_ref', salesforce.fields.CharField(blank=True, db_column='ETBillingZipRef__c', max_length=1300, null=True, verbose_name='ETBillingZip')),
                ('etbilling_city_ref', salesforce.fields.CharField(blank=True, db_column='ETBillingCityRef__c', max_length=1300, null=True, verbose_name='ETBillingCity')),
                ('studiengang_ref', salesforce.fields.CharField(blank=True, max_length=1300, null=True, verbose_name='Studiengang')),
                ('payment_terms_ref', salesforce.fields.CharField(blank=True, max_length=1300, null=True, verbose_name='Payment Terms')),
                ('is_dunning_invoice_trig', salesforce.fields.BooleanField(default=salesforce.backend.operations.DefaultedOnCreate(), verbose_name='Is Dunning Invoice')),
                ('invoice_date', salesforce.fields.DateField(blank=True, null=True)),
                ('mandate_go_cardless_id_auto', salesforce.fields.CharField(blank=True, max_length=1300, null=True, verbose_name='Mandate GoCardless Id')),
                ('reference_trig', salesforce.fields.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('status', salesforce.fields.CharField(blank=True, choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'db_table': 'Invoice__c',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', salesforce.fields.BooleanField(default=False, verbose_name='Deleted')),
                ('name', salesforce.fields.CharField(max_length=80, verbose_name='Rechnungsposten Name')),
                ('amount', salesforce.fields.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Gesamtpreis')),
                ('unit_price', salesforce.fields.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Einzelpreis')),
                ('type', salesforce.fields.CharField(blank=True, choices=[('TuitionFee', 'Studiengebühr'), ('SemesterFee', 'Semesterbeitrag'), ('SemesterDiscount', 'Rabatt auf Semesterbeitrag'), ('OverdueFee', 'Mahngebühr'), ('MatriculationFee', 'Immatrikulationsgebühr'), ('Dunning Fee', 'Dunning Fee')], max_length=255, null=True, verbose_name='Rechnungsposten')),
            ],
            options={
                'verbose_name': 'Rechnungsposten',
                'verbose_name_plural': 'Rechnungsposten',
                'db_table': 'InvoiceLineItem__c',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
