# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 09:21
from __future__ import unicode_literals

from django.db import migrations
import salesforce.backend.operations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_degreecourse_invoice_invoicelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', salesforce.fields.BooleanField(default=False, verbose_name='Deleted')),
                ('name', salesforce.fields.CharField(max_length=255, verbose_name='File Name')),
                ('is_private', salesforce.fields.BooleanField(default=salesforce.backend.operations.DefaultedOnCreate(), verbose_name='Private')),
                ('content_type', salesforce.fields.CharField(blank=True, max_length=120, null=True)),
                ('body_length', salesforce.fields.IntegerField(blank=True, null=True)),
                ('body', salesforce.fields.TextField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='degreecourse',
            options={'managed': False, 'verbose_name': 'Degree Course', 'verbose_name_plural': 'Degree Courses'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': False, 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'managed': False, 'verbose_name': 'Invoice Line Item', 'verbose_name_plural': 'Invoice Line Items'},
        ),
        migrations.AlterModelOptions(
            name='rabatt',
            options={'managed': False, 'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
    ]
