# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170728_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishabletoken',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
