# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170823_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='course',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
