# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_csvupload_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='course',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
